version: '3'
services:
  parsing_container:
    build: ./CodeParser
    networks:
      - comment_net
    environment:
      - FILENAME=${FILENAME}
    volumes:
      - ./files:/app/files/
      - ./logs:/app/logs/

  commenting_container:
    build: ./CommentCreator
    depends_on:
      - parsing_container
    networks:
      - comment_net
    environment:
      - FILENAME=${FILENAME}

  adding_comments_container:
    build: ./CommentPlacer
    depends_on:
      - commenting_container
    networks:
      - comment_net
    environment:
      - FILENAME=${FILENAME}
    volumes:
      - ./files:/app/files/
      - ./logs:/app/logs/

networks:
  comment_net:
    driver: bridge